# frozen_string_literal: true

source "https://rubygems.org"
gem "activerecord", ">= 8.0", "< 9"
gem "gritz", "~> 0.6.0"
gem "gritz-rails", "~> 0.2.0"
gem "railties", ">= 8.0", "< 9"
gem "sqlite3", ">= 2.9.6", "< 3"
