# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: catalog.proto

require 'google/protobuf'


descriptor_data = "\n\rcatalog.proto\x12\x07\x63\x61talog\"\x1c\n\x0eProductRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"\x1c\n\x0bListRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\"e\n\x0cProductReply\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0bprice_cents\x18\x03 \x01(\x05\x12\x12\n\nworker_pid\x18\x04 \x01(\x03\x12\x12\n\nrequest_id\x18\x05 \x01(\t2\x87\x01\n\x08Products\x12<\n\nGetProduct\x12\x17.catalog.ProductRequest\x1a\x15.catalog.ProductReply\x12=\n\x0cListProducts\x12\x14.catalog.ListRequest\x1a\x15.catalog.ProductReply0\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Catalog
  ProductRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("catalog.ProductRequest").msgclass
  ListRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("catalog.ListRequest").msgclass
  ProductReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("catalog.ProductReply").msgclass
end
