# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: catalog.proto for package 'catalog'

require 'grpc'
require 'catalog_pb'

module Catalog
  module Products
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'catalog.Products'

      rpc :GetProduct, ::Catalog::ProductRequest, ::Catalog::ProductReply
      rpc :ListProducts, ::Catalog::ListRequest, stream(::Catalog::ProductReply)
    end

    Stub = Service.rpc_stub_class
  end
end
