# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: lifecycle.proto for package 'rails_rpc'

require 'grpc'
require 'lifecycle_pb'

module RailsRpc
  module Lifecycle
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'rails_rpc.Lifecycle'

      rpc :Unary, ::RailsRpc::Request, ::RailsRpc::Response
      rpc :Upload, stream(::RailsRpc::Request), ::RailsRpc::Response
      rpc :Download, ::RailsRpc::Request, stream(::RailsRpc::Response)
      rpc :Chat, stream(::RailsRpc::Request), stream(::RailsRpc::Response)
    end

    Stub = Service.rpc_stub_class
  end
end
