# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lifecycle.proto

require 'google/protobuf'


descriptor_data = "\n\x0flifecycle.proto\x12\trails_rpc\"\x18\n\x07Request\x12\r\n\x05value\x18\x01 \x01(\t\"\x19\n\x08Response\x12\r\n\x05value\x18\x01 \x01(\t2\xde\x01\n\tLifecycle\x12\x30\n\x05Unary\x12\x12.rails_rpc.Request\x1a\x13.rails_rpc.Response\x12\x33\n\x06Upload\x12\x12.rails_rpc.Request\x1a\x13.rails_rpc.Response(\x01\x12\x35\n\x08\x44ownload\x12\x12.rails_rpc.Request\x1a\x13.rails_rpc.Response0\x01\x12\x33\n\x04\x43hat\x12\x12.rails_rpc.Request\x1a\x13.rails_rpc.Response(\x01\x30\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module RailsRpc
  Request = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rails_rpc.Request").msgclass
  Response = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rails_rpc.Response").msgclass
end
